const REF_DIR = 'wtfti';

function type(slug, concept, card) {
  return {
    slug,
    ref: `${REF_DIR}/${slug}.png`,
    concept,
    card,
  };
}

const genshinImageModule = {
  displayName: '原神TI 提瓦特宇宙 Card Generator',
  seriesLabel: '原神TI',
  outputPrefix: 'genshin',
  artStyle: 'inflatable-vinyl',
  cardMode: true,
  aspectRatio: '3:4',
  themeColor: '根据角色元素配色自动匹配',
  seriesTone:
    '把角色语境切到提瓦特冒险世界。' +
    '每张图都要像"原神角色气质 × WTFTI 自嘲人格"的混血角色：一眼能认出元素和角色影子，但仍然是原创的人格图鉴。' +
    '服装轮廓、发型、武器、元素符号、配色和道具都要借角色最典型的识别点，不要复刻官方立绘，不要 logo，不要 UI。',
  types: [
    type(
      'boss',
      '一个带雷电将军气质的充气手办角色。深紫黑和服铠甲、雷纹发饰、手持薙刀与待办卷轴，站姿像要当场接管整支队伍，周围漂浮雷元素纹章和被她改过三版的冒险计划表。表情冷静但压迫感很强。',
      {
        name: '雷霆调度员',
        number: '#001',
        code: 'B.O.S.S',
        backronym: 'Baal Operates Systematic Schedules',
        tagline: '散了吧，这支队伍我来带。',
        tags: ['⚡ 一道雷劈醒整支队', '📋 战前策划精确到秒', '😤 效率低的直接渡劫'],
        quote: '"不是我爱接手，是你们的计划真的需要抢救。"',
      },
    ),
    type(
      'nerd',
      '一个带阿贝多气质的充气手办角色。白金色炼金学者外套、记录本和炼金烧瓶堆满四周，胸前挂一串速写纸和配方卡。表情专注到近乎走火入魔。',
      {
        name: '须弥收藏癖',
        number: '#002',
        code: 'N.E.R.D',
        backronym: 'Never Ending Research Diary',
        tagline: '这个元素反应我研究过。',
        tags: ['🧪 炼金笔记比命还重', '📖 所有配方倒背如流', '🤓 看到未知就走不动路'],
        quote: '"知识不会说谎，但你的经验值会。"',
      },
    ),
    type(
      'ctrl',
      '一个带刻晴气质的充气手办角色。紫色利落短裙战斗服、雷元素发饰、手里拿着排得极满的日程板和执行清单，周围漂浮打勾到发亮的小任务牌。姿态笔直。',
      {
        name: '璃月效率怪',
        number: '#003',
        code: 'C.T.R.L',
        backronym: 'Commission Tasks Run Like Lightning',
        tagline: '你的进度条我已经帮你排好了。',
        tags: ['⚡ 委托清单日清日毕', '📊 效率就是正义', '😠 拖延等于犯罪'],
        quote: '"不是我催你，是任务不等人。"',
      },
    ),
    type(
      'mum',
      '一个带诺艾尔气质的充气手办角色。女仆骑士装、围裙口袋塞满创可贴、便当、热水杯和清洁工具，一边举着大剑一边还在替别人收拾残局。表情温柔但累到眼下发青。',
      {
        name: '蒙德老妈子',
        number: '#004',
        code: 'M.U.M',
        backronym: 'Making Unprepared Messes vanish',
        tagline: '你受伤了？来，我帮你处理。',
        tags: ['🛡️ 永远冲在收拾前线', '🍱 便当随时准备好', '😩 累到发青还在笑'],
        quote: '"没关系，交给我就好……虽然我也快倒了。"',
      },
    ),
    type(
      'simp',
      '一个带托马气质的充气手办角色。温暖管家装、手里抱着一大堆别人临时丢给他的任务牌和家务道具，身边漂浮钥匙串和写着"马上来"的小纸条。',
      {
        name: '提瓦特舔狗',
        number: '#005',
        code: 'S.I.M.P',
        backronym: 'Service Is My Priority',
        tagline: '你叫我一声，我翻山也来。',
        tags: ['🔑 随叫随到管家型', '📝 帮忙从不问原因', '😊 被使唤还觉得开心'],
        quote: '"不麻烦不麻烦，举手之劳而已嘛……第八次了。"',
      },
    ),
    type(
      'solo',
      '一个带魈气质的充气手办角色。青绿色夜叉风短披风、长枪和傩面元素，整个人被一圈淡青色仙气结界包住，社交邀请像撞到结界弹开。表情清冷。',
      {
        name: '绝云独行侠',
        number: '#006',
        code: 'S.O.L.O',
        backronym: 'Silence Over Loud Occasions',
        tagline: '别跟着我，我一个人习惯了。',
        tags: ['🏔️ 单人副本专精', '🚫 社交结界满级', '😶 沉默就是回答'],
        quote: '"不是讨厌你们，只是不需要。"',
      },
    ),
    type(
      'sleep',
      '一个带早柚气质的充气手办角色。狸猫尾巴兜帽、风元素小忍具、整个人缩在巨大枕头卷里像随时会再次睡着，周围漂浮没关掉的闹钟和小被团。',
      {
        name: '稻妻贪睡鬼',
        number: '#007',
        code: 'Z.Z.Z.Z',
        backronym: 'Zero Zero Zero Zeal',
        tagline: '再让我睡五分钟……五小时也行。',
        tags: ['😴 闹钟是摆设', '🍃 滚着滚着就睡了', '💤 从不主动起床'],
        quote: '"叫我起来干嘛……又没有紧急委托吧？"',
      },
    ),
    type(
      'game-r',
      '一个带达达利亚气质的充气手办角色。红黑利落战斗装、弓与水刃特效环绕，脚边堆着"再战一次"的挑战牌和打碎的练习靶。表情是越打越兴奋的上头笑。',
      {
        name: '至冬再来一把',
        number: '#008',
        code: 'G.A.M.E',
        backronym: 'Gladly Accepts More Encounters',
        tagline: '再来一局，这次我一定能赢。',
        tags: ['⚔️ 越输越上头', '🎯 练习靶换了八批', '🔥 停机时间为零'],
        quote: '"输了？那正好，说明还能更强。"',
      },
    ),
    type(
      'drunk',
      '一个带温迪气质的充气手办角色。吟游诗人披风、风元素羽毛、手里晃着酒杯和小琴，脚边散落酒桶塞和写到一半的诗。笑容轻飘飘。',
      {
        name: '风都真话王',
        number: '#009',
        code: 'D.R.N.K',
        backronym: 'Drunk Reveals Natural Knowledge',
        tagline: '喝完这杯，什么都告诉你。',
        tags: ['🍷 三杯后人格切换', '🎵 醉后真话特攻', '😏 酒醒就不认账'],
        quote: '"嗯？我昨晚说什么了？完全不记得呢~"',
      },
    ),
    type(
      'rebel',
      '一个带流浪者气质的充气手办角色。深蓝风帽和浮浪人轮廓、飘浮的风刃和被踩扁的规矩牌，双臂交叉、侧脸带嘲讽。',
      {
        name: '须弥反骨王',
        number: '#010',
        code: 'R.E.B.L',
        backronym: 'Rules? Everyone Breaks Limits',
        tagline: '你越让我听话，我越偏不。',
        tags: ['💨 规矩专用践踏者', '😏 叛逆写在脸上', '🖕 越管越反'],
        quote: '"听话是别人的事，我走我自己的风。"',
      },
    ),
    type(
      'oh-no',
      '一个带莫娜气质的充气手办角色。星空占星师披风、占星盘、命运水泡和写满预警的星图围着她转。表情是标准的"我不是吓你，我是真的算到了"。',
      {
        name: '星命预警机',
        number: '#011',
        code: 'O.H.N.O',
        backronym: 'Obviously Had Noted Outcomes',
        tagline: '我早就说过会出事了吧。',
        tags: ['🔮 出事前就算到了', '⚠️ 警告从不迟到', '😑 我说什么来着'],
        quote: '"不是我乌鸦嘴，是星盘不会说谎。"',
      },
    ),
    type(
      'thin-k',
      '一个带艾尔海森气质的充气手办角色。理性学者长披肩、绿金耳机装置和书页数据面板包围身体，头顶漂浮成团的思考框和删了又写的备忘纸。脸很冷，脑子却像开了十二个会。',
      {
        name: '教令院内耗王',
        number: '#012',
        code: 'T.H.N.K',
        backronym: 'Thoughts Haunting, Never-ending Knots',
        tagline: '表面冷静，脑子已经开了十二个会。',
        tags: ['🧠 脑内会议永不散场', '📝 删了又写写了又删', '😐 脸冷心更累'],
        quote: '"我没有在纠结，我在多角度论证。"',
      },
    ),
    type(
      'drama',
      '一个带芙宁娜气质的充气手办角色。舞台礼服、浪花和聚光灯同时环绕，表情在高傲、委屈、夸张表演欲之间切换，脚边散落法庭锤子和开场幕布。',
      {
        name: '枫丹大戏精',
        number: '#013',
        code: 'D.R.M.A',
        backronym: 'Drama Rules My Atmosphere',
        tagline: '我的情绪不是波动，是直接爆破。',
        tags: ['🎭 人生如戏全靠演技', '💧 泪点笑点一秒切', '🎬 走哪都是最后一幕'],
        quote: '"请注意，我不是在发脾气，我在表演人生。"',
      },
    ),
    type(
      'chill',
      '一个带钟离气质的充气手办角色。岩系长外套、玉石纹路和古典长柄武器，单手端着茶盏，另一只手随意垂着，脚边催促通知堆成小山但他看都不看。',
      {
        name: '岩系空电佛',
        number: '#014',
        code: 'C.H.I.L',
        backronym: 'Calm Habits Ignore Life',
        tagline: '你急你的，我喝我的茶。',
        tags: ['🍵 催命通知已读不回', '🪨 稳如磐石不可撼', '😌 佛系到近乎断电'],
        quote: '"急什么……原岩磨砺都要几千年。"',
      },
    ),
    type(
      'emo',
      '一个带申鹤气质的充气手办角色。冰白长发、符箓和红绳缠在身上，姿态微微蜷着，周围漂浮碎裂后重新拼起的冰片和被压住的情绪波纹。',
      {
        name: '仙府碎冰人',
        number: '#015',
        code: 'E.M.O',
        backronym: 'Emotions Mended Overnight',
        tagline: '碎了就碎了，拼回来就是。',
        tags: ['❄️ 冰封情绪不让看', '🩹 碎了又粘是常态', '😶 嘴上说没事心里全是事'],
        quote: '"我没有不开心，只是不想说话而已。"',
      },
    ),
    type(
      'atm-er',
      '一个带多莉气质的充气手办角色。夸张钱袋、宝箱、摩拉串和供能装置挂满全身，身边伸出好几只等着拿资源的小手，她自己快被薅空。',
      {
        name: '摩拉提款机',
        number: '#016',
        code: 'A.T.M',
        backronym: 'Always Transferring Mora',
        tagline: '怎么又是我付钱？',
        tags: ['💰 摩拉说没就没', '🤲 薅羊毛全找她', '😤 精明但永远被薅'],
        quote: '"做生意是互利！为什么每次亏的都是我！"',
      },
    ),
    type(
      'dior-s',
      '一个带枫原万叶气质的充气手办角色。轻薄浪人服、枫叶和风团缓缓绕身，整个人半躺在漂浮的叶片上。表情安静松弛。',
      {
        name: '枫叶躺平侠',
        number: '#017',
        code: 'D.I.O.R',
        backronym: 'Doing Idle Observations Routinely',
        tagline: '卷什么卷，先看会儿风景。',
        tags: ['🍁 躺着也能观天下', '🌬️ 低欲望高品质', '😴 输赢都不上头'],
        quote: '"与其追着跑，不如等风来。"',
      },
    ),
    type(
      'sexy',
      '一个带八重神子气质的充气手办角色。粉白巫女华服、狐狸耳意象和雷樱花瓣环绕，站姿很松、眼神带钓感，四周漂着已上钩的小心心。',
      {
        name: '稻妻钓系狐',
        number: '#018',
        code: 'S.E.X.Y',
        backronym: 'Subtly Enchanting, Xtra Yakumo',
        tagline: '我什么都没做，你自己靠过来的。',
        tags: ['🦊 不动声色就上钩', '💗 钓系天花板', '😏 危险又优雅'],
        quote: '"哎呀，又有人上当了呢~"',
      },
    ),
    type(
      'fake',
      '一个带凯亚气质的充气手办角色。白天体面骑兵队长外套和羽饰，背后裂成更危险的阴影层人格，手里拿着微笑面具和半杯酒。',
      {
        name: '骑兵队双面人',
        number: '#019',
        code: 'F.A.K.E',
        backronym: 'Facades Always Keep Everyone fooled',
        tagline: '我装得很好，但别真以为我没事。',
        tags: ['🎭 白天绅士夜晚疯', '🍸 微笑是最后防线', '😈 表面稳内心炸'],
        quote: '"放心，我很好——至少在上班的时候。"',
      },
    ),
    type(
      'malo',
      '一个带甘雨气质的充气手办角色。蓝白秘书风仙兽装、怀里抱着比人还高的公文卷和文件夹，角上挂着工位提醒铃，眼下有明显熬夜痕迹。',
      {
        name: '璃月加班仙',
        number: '#020',
        code: 'M.A.L.O',
        backronym: 'Mandatory All-nighters, Longing for Off-days',
        tagline: '优雅的外表下，全是加班的痕迹。',
        tags: ['📁 公文堆得比人高', '⏰ 加班三千年没调休', '😵 看着优雅实际快碎'],
        quote: '"请问……调休是什么意思？"',
      },
    ),
    type(
      'luck-y',
      '一个带可莉气质的充气手办角色。红色小斗篷、幸运四叶草、蹦蹦炸弹和宝箱卡片围着她跳，明明乱来却总把结果玩成中奖现场。',
      {
        name: '蒙德炸运王',
        number: '#021',
        code: 'L.U.C.K',
        backronym: 'Lucky, Unconsciously Creating Kabooms',
        tagline: '闭着眼扔都能炸出宝箱。',
        tags: ['🍀 运气好到离谱', '💣 乱来但总能赢', '😁 天选之子本人'],
        quote: '"嘿嘿，又中了~可莉最厉害了！"',
      },
    ),
    type(
      'joker',
      '一个带荒泷一斗气质的充气手办角色。夸张鬼角发型、赤色披风、鼓槌和应援旗乱飞，整个人处于嘴比脑子先到场的热闹状态。',
      {
        name: '花岗岩笑匠',
        number: '#022',
        code: 'J.O.K.E',
        backronym: 'Jokes Overwhelm, Keeping Everyone entertained',
        tagline: '场面？交给本大王就好。',
        tags: ['🥁 嘴比脑子先到场', '🎪 越整越离谱', '😆 快乐到停不下来'],
        quote: '"哈哈哈！不是我在搞笑，是世界需要我！"',
      },
    ),
    type(
      'shy',
      '一个带砂糖气质的充气手办角色。绿色炼金学者裙装、护目镜和实验瓶抱在胸前，身体缩得很小，像恨不得把自己塞进试验台后面。',
      {
        name: '实验室透明人',
        number: '#023',
        code: 'S.H.Y',
        backronym: 'Shrinking, Hiding, Yet caring',
        tagline: '那个……我其实想说……算了。',
        tags: ['🫣 存在感约等于零', '🧪 躲在试验台后面', '📝 话到嘴边又吞回'],
        quote: '"如果可以的话，能不能……不要看我？"',
      },
    ),
    type(
      'party',
      '一个带宵宫气质的充气手办角色。橙红祭典服、烟花棒、纸灯和小彩带炸得到处都是，整个人跳起来像刚把夜空点亮。',
      {
        name: '稻妻焊接工',
        number: '#024',
        code: 'P.A.R.T',
        backronym: 'Party Atmosphere Restored Totally',
        tagline: '冷场？不存在的，我看看哪里需要炸。',
        tags: ['🎆 一出场气氛拉满', '🔥 尴尬空气终结者', '😄 自带BGM的人'],
        quote: '"大家快看！要开始了要开始了！！"',
      },
    ),
    type(
      'than-k',
      '一个带班尼特气质的充气手办角色。冒险家护目镜、绷带和破破烂烂的幸运装备都在身上，明明刚倒霉完却还冲别人竖大拇指。',
      {
        name: '倒霉感恩王',
        number: '#025',
        code: 'T.H.N.K',
        backronym: 'Thankful, Hurt, Never Kvetching',
        tagline: '被骂了也想先说一句辛苦了。',
        tags: ['👍 倒霉也竖大拇指', '🩹 受伤先道歉', '😊 被骂还说谢谢'],
        quote: '"没事没事，是我不够好，下次一定！"',
      },
    ),
    type(
      'woc',
      '一个带派蒙气质的充气手办角色。漂浮小披风、星星发饰和记录板环绕身体，整个人离地一点点，表情像正在看别人翻车还顺便现场解说。',
      {
        name: '提瓦特吃瓜精',
        number: '#026',
        code: 'W.O.C',
        backronym: 'Watching Others Crumble',
        tagline: '我不参与，但我全程在场。',
        tags: ['🍿 翻车现场第一排', '🎙️ 实时解说不落场', '👀 什么都看见了'],
        quote: '"旅行者你看！那边又出事了！快去快去！"',
      },
    ),
    type(
      'love-r',
      '一个带神里绫华气质的充气手办角色。冰蓝和风长裙、折扇和雪花环绕，双手捧着一封还没送出的心动信笺，脚边漂着过量爱心。',
      {
        name: '稻妻上头姬',
        number: '#027',
        code: 'L.O.V.E',
        backronym: 'Longing Overflows, Very Emotionally',
        tagline: '心动一来根本收不住。',
        tags: ['💌 信写了八版没送出', '❄️ 克制但全写在脸上', '💗 恋爱滤镜直接拉满'],
        quote: '"这封信……还是下次再给吧。"',
      },
    ),
    type(
      'food-ie',
      '一个带香菱气质的充气手办角色。厨师围裙、锅勺、辣椒和锅巴围着转，怀里还抱着一大碗刚出锅的饭。',
      {
        name: '万民堂吃货',
        number: '#028',
        code: 'F.O.O.D',
        backronym: 'Feasting Overrides Other Duties',
        tagline: '先吃饱再说，热量是什么？',
        tags: ['🍜 锅巴先吃为敬', '🌶️ 辣度上限不存在', '😋 卡路里无效'],
        quote: '"来来来，先尝一口！减肥的事明天再说~"',
      },
    ),
    type(
      'talk-er',
      '一个带菲谢尔气质的充气手办角色。紫黑哥特裙、乌鸦使魔、舞台感手势和连发台词卷轴铺满四周，姿态像刚开始念第三段开场白。',
      {
        name: '永夜话痨姬',
        number: '#029',
        code: 'T.A.L.K',
        backronym: 'Talking Always, Long and Komplex',
        tagline: '等我说完这段……其实还有下一段。',
        tags: ['🦅 开口就停不下来', '🎭 台词永远有下一幕', '📜 只问一句能讲一章'],
        quote: '"吾乃断罪之皇女！容吾为汝讲述……喂别走啊！"',
      },
    ),
  ],
};

export default genshinImageModule;
