const REF_DIR = 'wtfti';

function type(slug, concept, card) {
  return {
    slug,
    ref: `${REF_DIR}/${slug}.png`,
    concept,
    card,
  };
}

const idvImageModule = {
  displayName: '庄园TI 第五人格宇宙 Card Generator',
  seriesLabel: '庄园TI',
  outputPrefix: 'idv',
  artStyle: 'inflatable-vinyl',
  cardMode: true,
  aspectRatio: '3:4',
  themeColor: '维多利亚哥特暗色调',
  seriesTone:
    '把角色语境切到第五人格的庄园世界。' +
    '每张图都要像"庄园角色职业感 × WTFTI 自嘲人格"的原创人格卡：维多利亚哥特、黑色幽默、道具讲故事。' +
    '服装、帽饰、工具、轮廓和小道具可以借用角色标志点，不要复刻官方海报，不要复杂场景，不要 logo。',
  types: [
    type(
      'boss',
      '一个带大副气质的充气手办角色。深蓝船长制服、航海帽、怀表和指令哨挂满全身，脚边摆着被排得明明白白的庄园路线图。姿态像正在强行接管一整队人的撤离节奏。',
      {
        name: '庄园总指挥',
        number: '#001',
        code: 'B.O.S.S',
        backronym: 'Barking Orders, Saving Survivors',
        tagline: '散了吧，撤退路线我已排好。',
        tags: ['🧭 路线图精确到秒', '📯 哨声就是命令', '😤 乱跑的别怪我'],
        quote: '"不是我爱指挥，是你们真的会迷路。"',
      },
    ),
    type(
      'nerd',
      '一个带囚徒气质的充气手办角色。凌乱研究服、电线、线圈和稿纸把他包起来，手里还抓着写满公式的图纸。眼神专注到有点疯。',
      {
        name: '庄园疯博士',
        number: '#002',
        code: 'N.E.R.D',
        backronym: 'Notes, Equations, Research, Data',
        tagline: '这个电路图我研究过。',
        tags: ['🔌 电线比命还重要', '📐 公式写满三面墙', '🤓 疯到忘记逃跑'],
        quote: '"别催我，你们不懂这个发现有多重要。"',
      },
    ),
    type(
      'ctrl',
      '一个带机械师气质的充气手办角色。齿轮裙撑、发条钥匙和小型傀儡围绕身体运作，手里同时拽着好几根操控线。',
      {
        name: '齿轮控制狂',
        number: '#003',
        code: 'C.T.R.L',
        backronym: 'Clockwork Tightly Regulates Lives',
        tagline: '连你们的逃生路线我都帮你排好了。',
        tags: ['⚙️ 傀儡同步率100%', '🔧 万物皆可机械化', '😠 失控就崩溃'],
        quote: '"只要所有零件按计划运转，就不会出错。"',
      },
    ),
    type(
      'mum',
      '一个带医生气质的充气手办角色。白色医生帽、药箱、绷带、针剂和急救工具塞满口袋，一边扶人一边自己已经累出黑眼圈。',
      {
        name: '庄园急诊妈',
        number: '#004',
        code: 'M.U.M',
        backronym: 'Mending Until Myself collapses',
        tagline: '来，我帮你治……我也快倒了。',
        tags: ['💉 绷带随身带三卷', '🩹 收拾残局专业户', '😩 治别人治到自己空血'],
        quote: '"没事没事，先救你……我还能撑一下。"',
      },
    ),
    type(
      'simp',
      '一个带小女孩气质的充气手办角色。褪色洋装、旧玩偶和一根总想抓住别人的丝线围着转，脚步小小地追着前方看不见的人影。',
      {
        name: '庄园跟屁虫',
        number: '#005',
        code: 'S.I.M.P',
        backronym: 'Silently Idolizing, Must be Present',
        tagline: '我可以跟着你吗？',
        tags: ['🧸 旧玩偶不离手', '🧵 看不到人就慌', '😊 被忽视也不走'],
        quote: '"你去哪我就去哪，不用理我也没关系。"',
      },
    ),
    type(
      'solo',
      '一个带守墓人气质的充气手办角色。灰黑铲具、墓土和小棺灯环绕，整个人像刚从地下安静地站起来，四周社交邀请被土层挡在外面。',
      {
        name: '地下独居客',
        number: '#006',
        code: 'S.O.L.O',
        backronym: 'Solitary Operations, Leave Others out',
        tagline: '一个人待着挺好的。',
        tags: ['⛏️ 地下比地上安全', '🚫 社交邀请已土葬', '😶 安静是最高礼仪'],
        quote: '"不是不合群，是地面太吵了。"',
      },
    ),
    type(
      'sleep',
      '一个带入殓师气质的充气手办角色。黑白礼服、棺椁小模型、羽毛和烛光围着身体缓慢漂浮，姿态安静得像快睡着。',
      {
        name: '永眠爱好者',
        number: '#007',
        code: 'Z.Z.Z.Z',
        backronym: 'Zealously Zeroing Zealous Zest',
        tagline: '再让我躺五分钟……永远也行。',
        tags: ['🕯️ 烛光就是催眠曲', '⚰️ 棺材比床舒服', '💤 活着不如躺着'],
        quote: '"别吵……让我再安静一会儿。"',
      },
    ),
    type(
      'game-r',
      '一个带杂技演员气质的充气手办角色。马戏服、燃烧弹球和弹跳道具围着转，动作幅度很大，像刚摔完一跤就准备再翻一轮。',
      {
        name: '马戏翻车王',
        number: '#008',
        code: 'G.A.M.E',
        backronym: 'Going Again, More Excitement',
        tagline: '再来一次，这次我一定能接住。',
        tags: ['🎪 摔了就再翻一轮', '🔥 火球越烫越上头', '🤡 输了也笑着走'],
        quote: '"刚才那个不算！再来再来！"',
      },
    ),
    type(
      'drunk',
      '一个带调酒师气质的充气手办角色。酒瓶、摇壶和溢出来的彩色酒液围着她旋转，裙摆像被酒精晕开，表情微醺又诚实。',
      {
        name: '庄园醉话筒',
        number: '#009',
        code: 'D.R.N.K',
        backronym: 'Drinks Reveal Neglected Knowledge',
        tagline: '喝完这杯，秘密就不是秘密了。',
        tags: ['🍸 一杯下去人格切换', '🫧 酒后全是真话', '😏 醒了什么都不承认'],
        quote: '"我说什么了？酒后的话不能当真哦~"',
      },
    ),
    type(
      'rebel',
      '一个带击球手气质的充气手办角色。球棒、护腕和砸碎的规矩牌散在脚边，站姿很横、肩膀往上一顶。',
      {
        name: '庄园砸场王',
        number: '#010',
        code: 'R.E.B.L',
        backronym: 'Rules? Every Bat Liberates',
        tagline: '你越不让，我越要。',
        tags: ['🏏 规矩是用来砸的', '😤 配合是不可能的', '💥 越管越暴'],
        quote: '"听话的人是怎么在庄园活下来的？"',
      },
    ),
    type(
      'oh-no',
      '一个带先知气质的充气手办角色。兜帽、猫头鹰羽毛、预警眼罩和提前写好的警示签漂浮四周。',
      {
        name: '庄园预言家',
        number: '#011',
        code: 'O.H.N.O',
        backronym: 'Omens Happen, Nobody cares, Oops',
        tagline: '我早就说会被抓了吧。',
        tags: ['🦉 出事之前就看到了', '⚠️ 警告从不迟到', '😑 说了你们不听'],
        quote: '"刚才那个位置我就不该让你去。"',
      },
    ),
    type(
      'thin-k',
      '一个带心理学家气质的充气手办角色。诊疗笔记、钟摆和情绪图表围着头顶打转，坐姿看似冷静，脑内像同时开了五场咨询室会议。',
      {
        name: '脑内诊疗室',
        number: '#012',
        code: 'T.H.N.K',
        backronym: 'Therapeutic Habits, Neurotic Knots',
        tagline: '表面在分析，内心已经开了五场会。',
        tags: ['🧠 脑子比庄园还复杂', '📊 情绪图表画了三版', '😐 看着冷其实在烧CPU'],
        quote: '"我不是在想太多，我在系统性评估。"',
      },
    ),
    type(
      'drama',
      '一个带歌剧演员气质的充气手办角色。夸张歌剧礼服、面具、聚光灯和撕开的幕布同时环绕，手势戏剧化到像连呼吸都要谢幕。',
      {
        name: '歌剧核爆员',
        number: '#013',
        code: 'D.R.M.A',
        backronym: 'Dramatic Reactions Magnify All',
        tagline: '情绪不是波动，是直接爆破。',
        tags: ['🎭 呼吸都要谢幕', '🎵 泪点笑点瞬间切', '💥 走哪都是高潮'],
        quote: '"谢幕？还早呢，我的表演才刚开始。"',
      },
    ),
    type(
      'chill',
      '一个带祭司气质的充气手办角色。白金祭司袍、门之法阵和安静漂浮的符纹围着转，手势慢、眼神淡。',
      {
        name: '入定空电祭',
        number: '#014',
        code: 'C.H.I.L',
        backronym: 'Calmly Handling Intense Lunacy',
        tagline: '你们慌你们的，我在这等门。',
        tags: ['🚪 开门关门不惊不扰', '🪬 稳到像没有情绪', '😌 电量1%也不慌'],
        quote: '"急什么……门会在该开的时候开。"',
      },
    ),
    type(
      'emo',
      '一个带画家气质的充气手办角色。深色画室装、画框和掉色颜料片围着身体，姿态微微蜷缩。',
      {
        name: '色块碎裂人',
        number: '#015',
        code: 'E.M.O',
        backronym: 'Emotions Melt Outward',
        tagline: '碎了就碎了，拼回去就是。',
        tags: ['🎨 情绪全画在色块上', '🩹 碎了又粘是日常', '😶 不说话不代表没事'],
        quote: '"我只是……在等颜料干。"',
      },
    ),
    type(
      'atm-er',
      '一个带玩具商气质的充气手办角色。巨大玩具箱、滑翔翼零件和礼物盒不停从她身边被分出去，别人都在拿，她自己却快被掏空。',
      {
        name: '庄园提款机',
        number: '#016',
        code: 'A.T.M',
        backronym: 'All Toys Missing',
        tagline: '怎么又是我出资源？',
        tags: ['🎁 礼物发到自己空了', '🤲 所有人都来拿', '😤 掏空了还在掏'],
        quote: '"我开箱子是为了大家！为什么只有我亏！"',
      },
    ),
    type(
      'dior-s',
      '一个带作曲家气质的充气手办角色。松垮华服、乐谱、节拍器和被他踩在脚边的进度钟表，动作慵懒。',
      {
        name: '乐谱躺平家',
        number: '#017',
        code: 'D.I.O.R',
        backronym: 'Doing Idle Orchestrations Regularly',
        tagline: '卷什么卷，先让我把这首曲子躺完。',
        tags: ['🎵 节拍器是催眠器', '⏰ 进度钟被踩扁了', '😴 慵懒才是高级'],
        quote: '"着什么急……好音乐需要时间。"',
      },
    ),
    type(
      'sexy',
      '一个带调香师气质的充气手办角色。精致香水裙、玻璃香瓶、残香涟漪和细高跟轮廓都很明显，她自己站得很稳，周围却飘满心动信号。',
      {
        name: '迷香危险源',
        number: '#018',
        code: 'S.E.X.Y',
        backronym: 'Scent Enchants, eXtremely Yielding',
        tagline: '我什么都没做，你自己走过来的。',
        tags: ['🌸 香气就是信号弹', '💗 无意识钓系', '😏 站着不动也有人上钩'],
        quote: '"我喷香水只是为了自己开心，真的。"',
      },
    ),
    type(
      'fake',
      '一个带杰克气质的充气手办角色。半边是绅士礼帽和体面长外套，半边裂成更锋利的暗影人格，手里拿微笑礼貌面具。',
      {
        name: '雾中双面绅',
        number: '#019',
        code: 'F.A.K.E',
        backronym: 'Fabricated Appearance Keeps Everyone calm',
        tagline: '看起来还在体面，实际快压不住了。',
        tags: ['🎩 白天绅士夜晚裂', '🌫️ 微笑是最好的伪装', '😈 里面的那个快出来了'],
        quote: '"别担心，一切都在我的掌控……之外。"',
      },
    ),
    type(
      'malo',
      '一个带律师气质的充气手办角色。旧西装、公文包、厚厚卷宗和庄园考勤钟都挂在身上，肩膀塌着、步子沉。',
      {
        name: '庄园加班鬼',
        number: '#020',
        code: 'M.A.L.O',
        backronym: 'Manor Always Loads Overtime',
        tagline: '班味永远散不掉。',
        tags: ['💼 公文包比人还重', '⏰ 考勤钟是噩梦', '😵 看一眼就知道刚加完班'],
        quote: '"请问……庄园有调休制度吗？"',
      },
    ),
    type(
      'luck-y',
      '一个带幸运儿气质的充气手办角色。简单朴素的衣装却被四叶草、幸运骰子和正好用上的道具围住。',
      {
        name: '庄园天选人',
        number: '#021',
        code: 'L.U.C.K',
        backronym: 'Lucky, Unbelievably Carelessly Kept safe',
        tagline: '什么都不会，但总能活下来。',
        tags: ['🍀 运气比技术强', '🎲 闭眼走都不被抓', '😁 天选之子认证'],
        quote: '"不是我厉害，是运气实在太好了。"',
      },
    ),
    type(
      'joker',
      '一个带小丑气质的充气手办角色。彩条舞台服、火箭冲刺零件、气球和夸张笑面全部炸开。',
      {
        name: '马戏失控王',
        number: '#022',
        code: 'J.O.K.E',
        backronym: 'Joking Outrageously, Keeping Everyone confused',
        tagline: '场面交给我，虽然可能会失控。',
        tags: ['🎈 气球炸到满天飞', '🚀 冲刺不知道终点', '😆 越离谱越开心'],
        quote: '"哈哈哈——等一下，这不是我计划的方向！"',
      },
    ),
    type(
      'shy',
      '一个带盲女气质的充气手办角色。安静长裙、手杖和低存在感的小音波围着身体，肩膀缩起来。',
      {
        name: '角落隐形人',
        number: '#023',
        code: 'S.H.Y',
        backronym: 'Staying Hidden, Yet sensitive',
        tagline: '那个……我在这里……算了。',
        tags: ['🤫 存在感低到消失', '🫥 恨不得缩进墙角', '📝 想说的话全吞了'],
        quote: '"不用找我了，我在角落就好……"',
      },
    ),
    type(
      'party',
      '一个带啦啦队员气质的充气手办角色。亮色运动套装、彩球、应援带和比分牌满天飞。',
      {
        name: '庄园气氛组',
        number: '#024',
        code: 'P.A.R.T',
        backronym: 'Pumping Atmosphere, Restoring Thrills',
        tagline: '冷场？不可能，我在呢。',
        tags: ['📣 应援声能震塌庄园', '🎊 尴尬空气一脚踢飞', '😄 社交能量永不断电'],
        quote: '"加油加油！我们一定能赢——大概！"',
      },
    ),
    type(
      'than-k',
      '一个带邮差气质的充气手办角色。旧制服、小邮包、信封和被雨打湿又烘干的纸张围着转，明明被嫌慢还在认真整理下一封信。',
      {
        name: '风雨感恩邮',
        number: '#025',
        code: 'T.H.N.K',
        backronym: 'Thankful, Humble, Never Kicking back',
        tagline: '被骂了也想先说一句辛苦了。',
        tags: ['📮 被嫌慢还在送', '🌧️ 风雨兼程不抱怨', '😊 挨骂先道歉'],
        quote: '"对不起送晚了……下一封我一定更快。"',
      },
    ),
    type(
      'woc',
      '一个带记者气质的充气手办角色。小本子、相机、记录笔和飞来飞去的消息纸片围着身体，姿态前倾准备记下别人翻车现场。',
      {
        name: '庄园狗仔队',
        number: '#026',
        code: 'W.O.C',
        backronym: 'Writing Observations Constantly',
        tagline: '我不参与，但我全程记录。',
        tags: ['📸 翻车现场首席记者', '📝 什么都记什么都看', '👀 不出手但永远在场'],
        quote: '"继续继续，就当我不存在~"',
      },
    ),
    type(
      'love-r',
      '一个带病患气质的充气手办角色。束带、钩索和过度拉满的关系线缠在四周，动作冲得很前。',
      {
        name: '庄园上头患',
        number: '#027',
        code: 'L.O.V.E',
        backronym: "Latching On, Very Eagerly",
        tagline: '心动一来直接冲，不留余地。',
        tags: ['💗 心动就是行动', '🔗 关系线拉满不松', '😵 先上头再说'],
        quote: '"等我冷静？不可能，已经冲了。"',
      },
    ),
    type(
      'food-ie',
      '一个带野人气质的充气手办角色。兽皮、野餐肉干、篝火小锅和大口啃食的动作都很明显。',
      {
        name: '荒野干饭兽',
        number: '#028',
        code: 'F.O.O.D',
        backronym: 'Feasting Obsessively, Others Dumbfounded',
        tagline: '先吃饱再逃，热量是什么？',
        tags: ['🍖 野餐级续命选手', '🔥 篝火就是厨房', '😋 逃跑前先把这口吃了'],
        quote: '"追我可以，等我吃完这口行吗？"',
      },
    ),
    type(
      'talk-er',
      '一个带小说家气质的充气手办角色。长外套、羽毛笔、稿纸和一串停不下来的旁白对话框围着头顶转。',
      {
        name: '庄园话唠怪',
        number: '#029',
        code: 'T.A.L.K',
        backronym: 'Talking All day, Long Komplex monologues',
        tagline: '等我讲完这段……其实还有下一章。',
        tags: ['✒️ 开口就是长篇大论', '📜 别人问一句他讲一章', '🗣️ 停不下来是天赋'],
        quote: '"且听我慢慢道来——喂，别跑啊！"',
      },
    ),
  ],
};

export default idvImageModule;
