const REF_DIR = 'wtfti';

function type(slug, concept, card) {
  return {
    slug,
    ref: `${REF_DIR}/${slug}.png`,
    concept,
    card,
  };
}

const narutoImageModule = {
  displayName: '忍者TI 火影忍者宇宙 Card Generator',
  seriesLabel: '忍者TI',
  outputPrefix: 'naruto',
  artStyle: 'inflatable-vinyl',
  cardMode: true,
  aspectRatio: '3:4',
  themeColor: '忍者世界暖色调配深色',
  seriesTone:
    '把角色语境切到火影忍者的忍村世界。' +
    '每张图都要像"忍者角色气质 × WTFTI 自嘲人格"的原创梗图角色：忍者头带、卷轴、苦无、查克拉、热血和社死感同时成立。' +
    '服装轮廓、忍具、配色和能力符号可以借角色最强识别点，但不要直接复刻官方战斗海报，不要复杂背景，不要 logo。',
  types: [
    type(
      'boss',
      '一个带纲手气质的充气手办角色。火影外袍、办公卷轴、医疗手套和一拳拍桌的姿态都很明显，脚边还堆着必须她来兜底的任务单。',
      {
        name: '火影接盘侠',
        number: '#001',
        code: 'B.O.S.S',
        backronym: 'Boss Over Sloppy Shinobis',
        tagline: '行了，这个任务我兜底。',
        tags: ['👊 一拳拍桌全场静', '📜 任务堆了三层楼', '😤 懒人统统给我跑圈'],
        quote: '"不是我想管，是你们一个比一个不靠谱。"',
      },
    ),
    type(
      'nerd',
      '一个带大蛇丸气质的充气手办角色。实验长袍、研究卷轴、蛇形标本和堆满的禁术笔记围着身体。眼神阴冷又过分专注。',
      {
        name: '禁术收藏狂',
        number: '#002',
        code: 'N.E.R.D',
        backronym: 'Ninjutsu Encyclopedia, Relentlessly Devouring',
        tagline: '这个术式我研究过。',
        tags: ['🐍 藏品比忍村还多', '📜 禁术笔记写满七卷', '🤓 研究到忘记叛逃'],
        quote: '"别碰我的笔记，你看不懂的。"',
      },
    ),
    type(
      'ctrl',
      '一个带千手扉间气质的充气手办角色。蓝色战甲、严谨护额和写满规则的卷轴围着身体，姿态笔直。',
      {
        name: '忍规制定机',
        number: '#003',
        code: 'C.T.R.L',
        backronym: 'Commanding, Tactical, Ruthlessly Logical',
        tagline: '连你们结印的顺序我都想统一。',
        tags: ['📏 规则比禁术还多', '⚡ 执行力堪比飞雷神', '😠 乱来就当场处理'],
        quote: '"没有规矩的忍者，不配上战场。"',
      },
    ),
    type(
      'mum',
      '一个带春野樱气质的充气手办角色。粉发医疗忍者装、急救包、查克拉手套和修补残局的小纸条都挂在身上。',
      {
        name: '木叶急救妈',
        number: '#004',
        code: 'M.U.M',
        backronym: 'Mending Useless Mates',
        tagline: '你们打完了？来，我收拾残局。',
        tags: ['💚 查克拉全用来治人', '🩹 绷带用比三代多', '😩 嘴硬心软第一人'],
        quote: '"下次能不能别这么拼……我治不过来了！"',
      },
    ),
    type(
      'simp',
      '一个带雏田气质的充气手办角色。浅色日向服、柔和白眼意象和写满暗恋滤镜的小心心围着身体，双手放在胸前。',
      {
        name: '木叶暗恋忍',
        number: '#005',
        code: 'S.I.M.P',
        backronym: 'Silently Idolizing, My Person',
        tagline: '你叫我一声，我就敢冲。',
        tags: ['👀 远距离偷看满级', '💗 暗恋滤镜拉满', '😊 为你变强全靠自驱'],
        quote: '"那个人……我一定要追上去。"',
      },
    ),
    type(
      'solo',
      '一个带佐助气质的充气手办角色。深色披风、草薙剑和冷色电光环绕，整个人站得很远很直，像自动把自己隔绝在热闹之外。',
      {
        name: '写轮眼独狼',
        number: '#006',
        code: 'S.O.L.O',
        backronym: 'Severed Others, Lone Operative',
        tagline: '别跟着我。',
        tags: ['⚡ 社交距离最大化', '🚫 组队邀请已拒绝', '😶 跟我说话超过三句就烦'],
        quote: '"我走我的路，不需要同伴。"',
      },
    ),
    type(
      'sleep',
      '一个带卡卡西气质的充气手办角色。面罩、护额、亲热天堂小书和打着哈欠的姿态都在，整个人懒散地半倚着。',
      {
        name: '木叶迟到王',
        number: '#007',
        code: 'Z.Z.Z.Z',
        backronym: 'Zero Zeal, Zero Zest',
        tagline: '抱歉，我在人生的道路上迷路了。',
        tags: ['😴 迟到是基本修养', '📖 摸鱼用灵魂阅读', '💤 打哈欠打出节奏感'],
        quote: '"嘛……迟到的理由我等会儿编一个。"',
      },
    ),
    type(
      'game-r',
      '一个带洛克李气质的充气手办角色。绿色紧身服、绷带、训练负重和不断追加的修炼清单围着身体。',
      {
        name: '热血加练狂',
        number: '#008',
        code: 'G.A.M.E',
        backronym: 'Going Again, Maximum Effort',
        tagline: '输了就加练，这次一定行！',
        tags: ['🏋️ 负重训练永不停', '🔥 努力比天赋管用', '🤕 摔了就再来一百次'],
        quote: '"如果做不到一千次正拳，就做两千次！"',
      },
    ),
    type(
      'drunk',
      '一个带自来也气质的充气手办角色。豪放长发、酒葫芦、写到一半的小说稿和被吹乱的护额围着身体，笑得很开。',
      {
        name: '蛤蟆醉话仙',
        number: '#009',
        code: 'D.R.N.K',
        backronym: 'Drunk Reveals Ninja Knowledge',
        tagline: '喝开了，什么秘密都能说。',
        tags: ['🍶 酒葫芦是必备忍具', '📝 醉后灵感爆发', '😏 酒醒了就赖账'],
        quote: '"嘿嘿嘿……这故事写进小说里绝对火。"',
      },
    ),
    type(
      'rebel',
      '一个带鸣人气质的充气手办角色。橙黑忍服、影分身残影、被踩在脚边的"不行"标签和猛冲出去的姿态。',
      {
        name: '忍道反骨仔',
        number: '#010',
        code: 'R.E.B.L',
        backronym: 'Rebellious Energy, Breaking Limits',
        tagline: '你说我做不到？那我偏要做给你看。',
        tags: ['🍥 不按套路出牌', '💨 影分身怼到你服', '😤 越不看好越要赢'],
        quote: '"我说了我会成为火影的！信不信由你！"',
      },
    ),
    type(
      'oh-no',
      '一个带药师兜气质的充气手办角色。眼镜、实验情报卷、蛇影和提前标好的风险图围绕身体。',
      {
        name: '情报预言家',
        number: '#011',
        code: 'O.H.N.O',
        backronym: 'Obviously Had Noted every Outcome',
        tagline: '我早说了会出事吧。',
        tags: ['🤓 情报比五影还全', '⚠️ 翻车路线提前标好', '😏 从不意外只有验证'],
        quote: '"别紧张，这一切都在我的预料之中。"',
      },
    ),
    type(
      'thin-k',
      '一个带日向宁次气质的充气手办角色。白眼纹理、八卦阵和宿命感很重的卷轴围着头顶旋转，姿态冷静克制。',
      {
        name: '命运内耗师',
        number: '#012',
        code: 'T.H.N.K',
        backronym: 'Thinking Hard, Nihilistic Knots',
        tagline: '表面冷静，脑内已经推演了三百个结局。',
        tags: ['🧠 宿命感比白眼还重', '🔄 内心戏演了三百集', '😐 看透了但说不出口'],
        quote: '"人的命运……真的能改变吗？"',
      },
    ),
    type(
      'drama',
      '一个带迪达拉气质的充气手办角色。晓袍轮廓、爆炸黏土、起爆符和炸开的艺术碎片同时环绕，动作夸张。',
      {
        name: '艺术即爆炸',
        number: '#013',
        code: 'D.R.M.A',
        backronym: 'Detonations Really Make Art',
        tagline: '我的情绪不是波动，是爆破。',
        tags: ['💣 情绪即爆炸', '🎨 艺术就是要炸场', '💥 低调是不可能的'],
        quote: '"艺术就是……一瞬间的美，嗯！"',
      },
    ),
    type(
      'chill',
      '一个带我爱罗气质的充气手办角色。砂葫芦、缓慢漂浮的沙粒和极简站姿，周围再吵也影响不到他。',
      {
        name: '沙漠空电佛',
        number: '#014',
        code: 'C.H.I.L',
        backronym: 'Calm, Half-asleep, Ignoring Life',
        tagline: '你急你的，我的沙子会自己动。',
        tags: ['🏜️ 沙盾自动运转', '😌 情绪稳如砂葫芦', '🪨 电量1%也不慌'],
        quote: '"……（已读不回）"',
      },
    ),
    type(
      'emo',
      '一个带宇智波鼬气质的充气手办角色。暗色晓袍、乌鸦羽毛、月读裂纹和被压回去的情绪波动围着身体。',
      {
        name: '写轮碎裂人',
        number: '#015',
        code: 'E.M.O',
        backronym: 'Emotions Mostly Obstructed',
        tagline: '看起来完整，其实刚把自己缝了一遍。',
        tags: ['🐦‍⬛ 乌鸦比情绪还多', '🩹 碎了无数次又拼回', '😶 不说话不代表没碎'],
        quote: '"原谅我……这是最后一次。"',
      },
    ),
    type(
      'atm-er',
      '一个带香燐气质的充气手办角色。查克拉锁链、补能标签和被多人同时伸手索取的供能管线缠在身边，她自己明显被用空了。',
      {
        name: '查克拉提款机',
        number: '#016',
        code: 'A.T.M',
        backronym: 'Always Transferring My chakra',
        tagline: '怎么又是我当充电宝？',
        tags: ['⚡ 查克拉说没就没', '🤲 所有人都来咬', '😤 补能补到自己空血'],
        quote: '"谁再来咬我一口试试——算了你咬吧。"',
      },
    ),
    type(
      'dior-s',
      '一个带鹿丸气质的充气手办角色。木叶背心、将棋、影子术和被他随手丢开的任务单，整个人半躺半坐。',
      {
        name: '影子躺平王',
        number: '#017',
        code: 'D.I.O.R',
        backronym: 'Doing Idle Operations as Routine',
        tagline: '麻烦死了，先让我躺会儿。',
        tags: ['♟️ 将棋就是人生', '☁️ 看云比执行任务重要', '😴 低欲望终极体'],
        quote: '"啊……好麻烦。"',
      },
    ),
    type(
      'sexy',
      '一个带小南气质的充气手办角色。蓝白纸花发饰、纸片翅膀和极简冷艳长袍环绕身体，站姿很稳，周围漂着被她无意吸引的心动符号。',
      {
        name: '纸花冷艳源',
        number: '#018',
        code: 'S.E.X.Y',
        backronym: 'Silent, Exquisite, eXtra Yakuza-cool',
        tagline: '我什么都没做，你自己靠过来的。',
        tags: ['🌸 站着不动就有人做梦', '💗 冷到发光的吸引力', '😏 危险但忍不住靠近'],
        quote: '"不要靠近我——我说了不要。"',
      },
    ),
    type(
      'fake',
      '一个带带土气质的充气手办角色。半边是面具和体面披风，半边裂成更阴暗的查克拉漩涡，脚边散落两套完全不同的人设碎片。',
      {
        name: '面具双面忍',
        number: '#019',
        code: 'F.A.K.E',
        backronym: 'Fabricating A Kindred Exterior',
        tagline: '看起来还在演正常人，实际快裂了。',
        tags: ['🎭 面具不止一张', '🌀 里面的人格快出来了', '😈 白天演好人夜晚崩'],
        quote: '"这个世界……让我来重建吧。"',
      },
    ),
    type(
      'malo',
      '一个带大和气质的充气手办角色。木遁纹理、工地队长式忍者背心、搭到一半的任务木桩和加班记录卷轴堆在身边。',
      {
        name: '木叶加班柱',
        number: '#020',
        code: 'M.A.L.O',
        backronym: 'Mandatory All-night Laboring Operative',
        tagline: '又加班了……这是第几个通宵？',
        tags: ['🪵 木遁用来搭加班桌', '⏰ 通宵记录忍界第一', '😵 看一眼就是刚执行完任务的脸'],
        quote: '"带这群人比打S级任务还累。"',
      },
    ),
    type(
      'luck-y',
      '一个带波风水门气质的充气手办角色。金色闪光速度残影、飞雷神苦无和一连串刚好踩中的好运节点围着身体。',
      {
        name: '黄色闪光运',
        number: '#021',
        code: 'L.U.C.K',
        backronym: 'Lightning-fast, Unbelievably Clutch Kunai',
        tagline: '做什么都能刚好快半拍。',
        tags: ['⚡ 闪到运气都追不上', '🍀 刚好踩中每个好运点', '😁 帅就是最大的运气'],
        quote: '"唔，看来刚好赶上了。"',
      },
    ),
    type(
      'joker',
      '一个带阿凯气质的充气手办角色。浓眉、绿色紧身衣、夸张热血手势和青春火焰全部拉满。',
      {
        name: '青春火焰怪',
        number: '#022',
        code: 'J.O.K.E',
        backronym: 'Joyful Outbursts, Keeping Everyone pumped',
        tagline: '青春的力量是无限的！',
        tags: ['🔥 热血到自己着火', '💪 浓眉是战斗力来源', '😆 快乐到整个忍村都知道'],
        quote: '"燃烧吧！青春！——等一下裤子着了。"',
      },
    ),
    type(
      'shy',
      '一个带志乃气质的充气手办角色。高领外套、墨镜、虫群和很低的存在感同时出现，身体缩在衣领里。',
      {
        name: '虫群隐身忍',
        number: '#023',
        code: 'S.H.Y',
        backronym: 'Silent, Hidden, Yet involved',
        tagline: '那个……你们忘了我在这里。',
        tags: ['🕶️ 存在感低到忍界除名', '🐛 虫子比朋友多', '😶 说了三句被忽略两句半'],
        quote: '"为什么……每次分组都忘了我？"',
      },
    ),
    type(
      'party',
      '一个带奇拉比气质的充气手办角色。墨镜、说唱节奏线、墨迹音符和夸张手势满场飞。',
      {
        name: '雷影说唱怪',
        number: '#024',
        code: 'P.A.R.T',
        backronym: 'Party Activated, Rhyme Time',
        tagline: '冷场？让八尾来给你们嗨一个。',
        tags: ['🎤 说唱能力全忍界第一', '🐙 八尾是最佳拍档', '😄 嗨到敌人放弃抵抗'],
        quote: '"Yeah~! Bakayaro Konoyaro~!"',
      },
    ),
    type(
      'than-k',
      '一个带天天气质的充气手办角色。卷轴武器、飞镖包和整理得整整齐齐的工具挂满全身，明明被指出问题还在第一时间补位。',
      {
        name: '忍具感恩侠',
        number: '#025',
        code: 'T.H.N.K',
        backronym: 'Thankful, Hardworking, Never Kicking up fuss',
        tagline: '被骂了也先整理好装备再说。',
        tags: ['🔧 忍具整理强迫症', '🎯 被嫌弃还在配合', '😊 挨批先反省自己'],
        quote: '"对不起……是我准备不够充分。"',
      },
    ),
    type(
      'woc',
      '一个带佐井气质的充气手办角色。墨画卷轴、速写本和安静围观的小表情纸片都在，姿态站得不近不远。',
      {
        name: '忍界吃瓜师',
        number: '#026',
        code: 'W.O.C',
        backronym: 'Watching, Observing, Chronicling',
        tagline: '我不参与，但我全程记下来了。',
        tags: ['🖌️ 围观后默默画下来', '📒 表情管理满分', '👀 什么都看到了但不出声'],
        quote: '"我画了一幅画，是你们刚才翻车的样子。"',
      },
    ),
    type(
      'love-r',
      '一个带井野气质的充气手办角色。明亮忍装、花朵、镜子和一秒切满的恋爱滤镜围着身体。',
      {
        name: '花忍上头王',
        number: '#027',
        code: 'L.O.V.E',
        backronym: 'Loving Obsessively, Very Emotionally',
        tagline: '心动一来直接上头，冷静不存在的。',
        tags: ['💐 恋爱滤镜永远在线', '💗 心动就是行动', '😵 脑补已经到结婚了'],
        quote: '"等一下——他刚才是不是看了我一眼？！"',
      },
    ),
    type(
      'food-ie',
      '一个带丁次气质的充气手办角色。零食袋、团子签、薯片碎和不断续上的能量盘围着身体。',
      {
        name: '木叶干饭兽',
        number: '#028',
        code: 'F.O.O.D',
        backronym: 'Feasting Overrides Other Duties',
        tagline: '先吃饱再打，热量是查克拉。',
        tags: ['🍡 团子是忍具之首', '🍖 战斗前先续一碗', '😋 减肥是禁术'],
        quote: '"别叫我胖！我只是热量储备比较多！"',
      },
    ),
    type(
      'talk-er',
      '一个带犬冢牙气质的充气手办角色。犬牙护额、忍犬爪印、连珠炮式对话条和很大的肢体动作。',
      {
        name: '忍犬话炮筒',
        number: '#029',
        code: 'T.A.L.K',
        backronym: 'Talking All day, Loudly and Krazily',
        tagline: '等我说完——其实我也不知道要说什么。',
        tags: ['🐕 开口音量全忍界最高', '💬 对话框堆到屏幕外', '🗣️ 停不下来是体质'],
        quote: '"听我说！听我说！——赤丸你也觉得对吧！"',
      },
    ),
  ],
};

export default narutoImageModule;
